/* soapESBServiceSoapProxy.h
   Generated by gSOAP 2.8.24 from ESBServiceWSDL.h

gSOAP XML Web services tools
Copyright (C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef soapESBServiceSoapProxy_H
#define soapESBServiceSoapProxy_H
#include "soapH.h"

class SOAP_CMAC ESBServiceSoapProxy : public soap
{ public:
	/// Endpoint URL of service 'ESBServiceSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in ESBServiceWSDL.h (non-static)
	/// Constructor
	ESBServiceSoapProxy();
	/// Copy constructor
	ESBServiceSoapProxy(const ESBServiceSoapProxy& rhs);
	/// Construct from another engine state
	ESBServiceSoapProxy(const struct soap&);
	/// Constructor with endpoint URL
	ESBServiceSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	ESBServiceSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	ESBServiceSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	ESBServiceSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor deletes deserialized data and engine context
	virtual	~ESBServiceSoapProxy();
	/// Initializer used by constructors
	virtual	void ESBServiceSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Create a new copy
	virtual	ESBServiceSoapProxy *copy() /*SOAP_PURE_VIRTUAL*/;
	/// Copy assignment
	ESBServiceSoapProxy& operator=(const ESBServiceSoapProxy&);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'ESBOperation' (returns error code or SOAP_OK)
	virtual	int ESBOperation(std::string session, std::string inputs, std::string &results) { return this->ESBOperation(NULL, NULL, session, inputs, results); }
	virtual	int ESBOperation(const char *endpoint, const char *soap_action, std::string session, std::string inputs, std::string &results);
};
#endif
