/* soapClient.cpp
   Generated by gSOAP 2.8.24 from ESBServiceWSDL.h

gSOAP XML Web services tools
Copyright (C) 2000-2015, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#if defined(__BORLANDC__)
#pragma option push -w-8060
#pragma option push -w-8004
#endif
#include "soapH.h"

SOAP_SOURCE_STAMP("@(#) soapClient.cpp ver 2.8.24 2015-12-14 00:51:48 GMT")


SOAP_FMAC5 int SOAP_FMAC6 soap_call___ns1__ESBOperation(struct soap *soap, const char *soap_endpoint, const char *soap_action, std::string session, std::string inputs, std::string &results)
{	struct __ns1__ESBOperation soap_tmp___ns1__ESBOperation;
	struct __ns1__ESBOperationResponse *soap_tmp___ns1__ESBOperationResponse;
	if (soap_endpoint == NULL)
		soap_endpoint = "http://localhost:9000";
	if (soap_action == NULL)
		soap_action = "";
	soap_tmp___ns1__ESBOperation.session = session;
	soap_tmp___ns1__ESBOperation.inputs = inputs;
	soap_begin(soap);
	soap->encodingStyle = NULL;
	soap_serializeheader(soap);
	soap_serialize___ns1__ESBOperation(soap, &soap_tmp___ns1__ESBOperation);
	if (soap_begin_count(soap))
		return soap->error;
	if (soap->mode & SOAP_IO_LENGTH)
	{	if (soap_envelope_begin_out(soap)
		 || soap_putheader(soap)
		 || soap_body_begin_out(soap)
		 || soap_put___ns1__ESBOperation(soap, &soap_tmp___ns1__ESBOperation, "-ns1:ESBOperation", NULL)
		 || soap_body_end_out(soap)
		 || soap_envelope_end_out(soap))
			 return soap->error;
	}
	if (soap_end_count(soap))
		return soap->error;
	if (soap_connect(soap, soap_url(soap, soap_endpoint, NULL), soap_action)
	 || soap_envelope_begin_out(soap)
	 || soap_putheader(soap)
	 || soap_body_begin_out(soap)
	 || soap_put___ns1__ESBOperation(soap, &soap_tmp___ns1__ESBOperation, "-ns1:ESBOperation", NULL)
	 || soap_body_end_out(soap)
	 || soap_envelope_end_out(soap)
	 || soap_end_send(soap))
		return soap_closesock(soap);
	if (!&results)
		return soap_closesock(soap);
	soap_default_std__string(soap, &results);
	if (soap_begin_recv(soap)
	 || soap_envelope_begin_in(soap)
	 || soap_recv_header(soap)
	 || soap_body_begin_in(soap))
		return soap_closesock(soap);
	soap_tmp___ns1__ESBOperationResponse = soap_get___ns1__ESBOperationResponse(soap, NULL, "-ns1:ESBOperationResponse", NULL);
	if (!soap_tmp___ns1__ESBOperationResponse || soap->error)
		return soap_recv_fault(soap, 0);
	if (soap_body_end_in(soap)
	 || soap_envelope_end_in(soap)
	 || soap_end_recv(soap))
		return soap_closesock(soap);
	results = soap_tmp___ns1__ESBOperationResponse->results;
	return soap_closesock(soap);
}

#if defined(__BORLANDC__)
#pragma option pop
#pragma option pop
#endif

/* End of soapClient.cpp */
